import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DefaultSeo } from 'next-seo';
import ClientLayout from "./ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <head>
        <DefaultSeo
          title="Marketplace MMORPG SEA"
          description="Jual beli item, gold, jasa game MMORPG Asia Tenggara. Aman, cepat, terpercaya."
          openGraph={{
            type: 'website',
            locale: 'id_ID',
            url: 'https://yourdomain.com',
            siteName: 'Marketplace MMORPG SEA',
          }}
          twitter={{
            cardType: 'summary_large_image',
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
