#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

# Run the accessibility checks through npm script
if npm run test:axe; then
  exit 0
else
  if [ $? -eq 1 ] && grep -q "ECONNREFUSED\|ERR_CONNECTION_REFUSED" axe-report.json; then
    echo "\033[33mWarning: Could not start development server. Skipping accessibility checks.\033[0m"
    exit 0
  fi
  echo "\033[31mError running accessibility checks.\033[0m"
  exit 1
fi
